
#
#local为本机环境(127.0.0.1)配置
#

##-----------------------------------server-------------------------------------------
server:
  #服务端口 TODO 修改端口
  port: 9511
  #服务baseURl TODO 修改BaseURL
  servlet:
    context-path: /cjyc/ccc
  #https访问
#  ssl:
#    key-store: classpath:server.jks
#    key-store-password: Vf1@MFJkhRyOSxm2
#    keyStoreType: JKS

##-----------------------------------spring-------------------------------------------
spring:
  #项目名 TODO 修改项目名
#  application:
#    name: cjyc-server-api

  ##静态资源本地位置(最后的/记得加) TODO 修改静态资源路径
  #resources:
    #static-locations: file:D:\\upload\\
  #静态资源过滤url
  #mvc:
    #static-path-pattern: /**

  ##actuator管理
  management:
    endpoints:
      enabled-by-default: true
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: always

  ##数据源 TODO 修改数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.96.231:3306/ju_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Qaz123$%^231#
    #连接池
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: CjycHikari
      max-lifetime: 1800000
      connection-timeout: 30000
      #connection-test-query: select 1

  ##缓存 TODO 修改缓存
  redis:
    host: 192.168.225.11
    port: 6379
    #Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    timeout: 1000ms
    #连接池，redis2.x默认连接池
    jedis:
      pool:
        max-active: 32
        max-idle: 16
        max-wait: 300ms
        min-idle: 8
#    lettuce:
#      pool:
#        #连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-active: 32
#        #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-wait: 300ms
#        #连接池中的最大空闲连接 默认 8
#        max-idle: 16
#        #连接池中的最小空闲连接 默认 0
#        min-idle: 8

##-----------------------------------logging-------------------------------------------
##日志
logging:
  level:
    com.cjyc.system.db.dao: debug



##-----------------------------------cjyc-------------------------------------------
cjyc:
  swagger:
    enabled: true
    title: CJYC Api
    description: 韵车项目接口文档
    version: 2.0.1
    basePackage: com.cjyc.api.controller
    groupName: CJYC Server Api
    usePathMapping: false


  #短信
  sms:
    miaoxin:
      enabled: true
      server: http://www.51miaoxin.com
      account: cjwlhy
      secret: ba9jet8miibxepu4gb5q
  #推送
  push:
    jiguang:
      enabled: true
      appKey: 7d431e42dfa6a6d693ac2d04
      masterSecret: 5e987ac6d2e04d95a9d8f0d1

  #
##-----------------------------------cjyc-tpl-------------------------------------------

        

