
#
#local为本机环境(127.0.0.1)配置
#

##-----------------------------------server-------------------------------------------
server:
  #服务端口 TODO 修改端口
  port: 9502
  #服务baseURl TODO 修改BaseURL
  servlet:
    context-path: /cjyc/salesman
  #https访问
#  ssl:
#    key-store: classpath:server.jks
#    key-store-password: Vf1@MFJkhRyOSxm2
#    keyStoreType: JKS

##-----------------------------------spring-------------------------------------------
spring:
  main:
    allow-bean-definition-overriding: true
  ##actuator管理
  management:
    endpoints:
      enabled-by-default: true
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: always

  ##数据源 TODO 修改数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.96.231:3306/ju_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Qaz123$%^231#
    #连接池
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: CjycHikari
      max-lifetime: 1800000
      connection-timeout: 30000
      #connection-test-query: select 1

  ##缓存 TODO 修改缓存
  redis:
    host: 192.168.225.11
    port: 6379
    #Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    timeout: 1000ms
    #连接池，redis2.x默认连接池
    jedis:
      pool:
        max-active: 32
        max-idle: 16
        max-wait: 300ms
        min-idle: 8

##-----------------------------------logging-------------------------------------------
##日志
logging:
  level:
    #root: debug
    com.cjyc.salesman.api: debug
    com.cjyc.common.model.dao: debug



##-----------------------------------cjyc-------------------------------------------
cjyc:
  swagger:
    enabled: true
    title: CJYC业务员Api
    description: 韵车项目接口文档
    version: 2.0.1
    basePackage: com.cjyc.salesman.api.controller
    groupName: CJYC-Salesman-Api
    usePathMapping: false

  #短信
  sms:
    ##短信时效(分钟)
    expires: 5
    ##单日最大发送条数
    daylimit: 20
    miaoxin:
      enabled: true
      server: http://www.51miaoxin.com
      account: cjwlhy
      secret: ba9jet8miibxepu4gb5q

  #推送
  push:
    jiguang:
      enabled: true
      appKey: 8a4abf674ba61fc9c47d6616
      masterSecret: 6fc93a75e2f813f4798e88ff

  #支付
  pay:
    ping++:
      businessCode: 200604000004527
      apikey: sk_test_40WD00COyLKOKKCiD8vH04qL
      customer:
        appid: app_WHKWv9XDWTyPz1G8
        webhooks: http://39.106.134.87:80/manycc/pingpay/webhooksNotice
      driver:
        appid: app_XzvvzPDmDm1GbTi1
        webhooks: http://39.106.134.87:80/manycc/pingpay/webhooksNotice
      salesman:
        appid: app_LSm9WLS4SmLSSC48
        webhooks: http://39.106.134.87:80/manycc/pingpay/webhooksNotice


  ##SALT
  #salt:
    #customer: YCcustomersalt
    #driver: YCdriversalt
    #salesman: YCsalesmansalt

  ##TOKEN
  token:
    ##过期时间（秒）
    expires: 1800




        

