
#
#local为本机环境(127.0.0.1)配置
#

##-----------------------------------server-------------------------------------------
server:
  #服务端口 TODO 修改端口
  port: 9502
  #服务baseURl TODO 修改BaseURL
  servlet:
    context-path: /cjyc/salesman
  #https访问
#  ssl:
#    key-store: classpath:server.jks
#    key-store-password: Vf1@MFJkhRyOSxm2
#    keyStoreType: JKS
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000
##-----------------------------------spring-------------------------------------------
spring:
  main:
    allow-bean-definition-overriding: true
  ##actuator管理
  management:
    endpoints:
      enabled-by-default: true
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: always

  ##数据源 TODO 修改数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.96.231:3306/ju_test_dev?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Qaz123$%^231#
    #连接池
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: SalemanHikari
      max-lifetime: 1800000
      connection-timeout: 30000
      #connection-test-query: select 1

  ##缓存 TODO 修改缓存
  redis:
    host: 39.107.96.231
    port: 6379
    password: Qaz123$%^Qaz123$%^Qaz123$%^Qaz123$%^Qaz123$%^
    #Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 1
    timeout: 1000ms
    #连接池，redis2.x默认连接池
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 32
        #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 300ms
        #连接池中的最大空闲连接 默认 8
        max-idle: 16
        #连接池中的最小空闲连接 默认 0
        min-idle: 8
    #连接池，redis2.x默认连接池
#    jedis:
#      pool:
#      max-active: 32
#      max-idle: 16
#      max-wait: 300ms
#      min-idle: 8

##-----------------------------------logging-------------------------------------------
##日志
logging:
  level:
    #root: debug
    com.cjyc.salesman.api: debug
    com.cjyc.common.model.dao: debug



##-----------------------------------cjyc-------------------------------------------
cjkj:
  dept_customer_id: 100000
  dept_driver_id: 110000
  dept_admin_id: 120000
  customer:
    password: 123456
    partner_role_id: "1204691365000458242"
  driver:
    password: 123456
  salesman:
    password: 123456
  web:
    clientId: "1186108891007336449"
    clientSecret: acffa1064e9a629d3140e5b36be31bd3
    grantType: password
    password: ${cjkj.salesman.password} #使用后不能修改
  carries_menu_ids: >
    1166601727922446337,
    1199275446849839105,
    1199276101425504258,
    1199275720784027649
  carries_mgr_menu_ids: >
    1166601727922446337,
    1199275446849839105,
    1199276101425504258,
    1199275720784027649
  carries_menus:
    enable: true
  carrier_super_role_name: 承运商超级管理员
  carrier_common_role_name: 承运商管理员
  carrier_sub_driver_role_name: 下属司机
  carrier_personal_driver_role_name: 个人司机
  customer_client_role_name: C端客户
  customer_key_role_name: 大客户
  customer_copartner_role_name: 合伙人

  signature: 韵车物流

cjyc:
  swagger:
    enabled: true
    title: CJYC业务员Api
    description: 韵车项目接口文档
    version: 2.0.1
    basePackage: com.cjyc.salesman.api.controller
    groupName: Salesman
    usePathMapping: false
  salesman:
    clientId: "1186108891007336449"
    clientSecret: acffa1064e9a629d3140e5b36be31bd3
    grantType: mobile

  #短信
  sms:
    ##短信时效(秒)
    expires: 300
    ##单日最大发送条数
    daylimit: 20
    miaoxin:
      enabled: true
      server: http://www.51miaoxin.com
      account: cjwlhy
      secret: ba9jet8miibxepu4gb5q

  #推送
  push:
    jiguang:
      enabled: true
      appKey: 8a4abf674ba61fc9c47d6616
      masterSecret: 6fc93a75e2f813f4798e88ff

  #支付
  pay:
    ping++:
      businessCode: 200604000004527
      apikey: sk_test_40WD00COyLKOKKCiD8vH04qL
      customer:
        appid: app_WHKWv9XDWTyPz1G8
        webhooks: http://39.106.134.87:80/manycc/pingpay/webhooksNotice
      driver:
        appid: app_XzvvzPDmDm1GbTi1
        webhooks: http://39.106.134.87:80/manycc/pingpay/webhooksNotice
      salesman:
        appid: app_LSm9WLS4SmLSSC48
        webhooks: http://39.106.134.87:80/manycc/pingpay/webhooksNotice

    #车系logo
  carSeries:
    logoImg: https://cjwl-test-bucket.obs.cn-north-1.myhuaweicloud.com:443/

  ##SALT
  #salt:
    #customer: YCcustomersalt
    #driver: YCdriversalt
    #salesman: YCsalesmansalt

  ##TOKEN
  token:
    ##过期时间（秒）
    expires: 1800




        

