















  ##极光推送
  JPush:
      appKey: 8a4abf674ba61fc9c47d6616
      masterSecret: 6fc93a75e2f813f4798e88ff


  ##ping++
  Ping++:
      businessCode: 200604000004527
      apiKey: sk_live_n1mzvDOq9CO00COCWP4uXv10
      #apikey: sk_test_40WD00COyLKOKKCiD8vH04qL
      customer:
         appid: app_nzjv5C5qLKGSbH0q
         webhooks: http://39.106.134.87:80/manycc/pingpay/webhooksNotice
      driver:
         appid: app_Wv9WnDKaD4GKqHib
         webhooks: http://39.106.134.87:80/manycc/pingpay/webhooksNotice
      salesman:
         appid: app_jjnL8KWjLm18SCqv
         webhooks: http://39.106.134.87:80/manycc/pingpay/webhooksNotice

  ##SALT
  SALT:
      customer_salt: YCcustomersalt
      driver_salt: YCdriversalt
      salesman_salt: YCsalesmansalt