
#
#local为本机环境(127.0.0.1)配置
#

server:
  #服务端口
  port: 9511
  #https访问
#  ssl:
#    key-store: classpath:server.jks
#    key-store-password: Vf1@MFJkhRyOSxm2
#    keyStoreType: JKS
ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000

spring:
  main:
    allow-bean-definition-overriding: true
  ##静态资源本地位置(最后的/记得加)
  #  resources:
  #    static-locations: file:D:\\upload\\
  #  #静态资源过滤url
  #  mvc:
  #    static-path-pattern: /**

  ##actuator管理
  management:
    endpoints:
      enabled-by-default: true
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: always

  ##数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.96.231:3306/ju_test_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false #开发
    username: root
    password: Qaz123$%^231#
    #连接池
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: WebHikari
      max-lifetime: 1800000
      connection-timeout: 30000
      #connection-test-query: select 1

    ##Mybatis
    ##mybatis:
    ##mapper-locations: classpath:mapper/*Mapper.xml
    ##type-aliases-package: com.cjyc.customer.api.entity
    #config-location : classpath:mybatis-config.xml

  ##缓存
  redis:
    host: 39.107.96.231
    port: 6379
    password: Qaz123$%^Qaz123$%^Qaz123$%^Qaz123$%^Qaz123$%^
    #Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    timeout: 1000ms
    #连接池，redis2.x默认连接池
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 32
        #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 300ms
        #连接池中的最大空闲连接 默认 8
        max-idle: 16
        #连接池中的最小空闲连接 默认 0
        min-idle: 8

  messages:
    basename: i18n/msg
##-----------------------------------logging-------------------------------------------
##日志
logging:
  level:
    #root: debug
    com.cjyc.carcircle.api: debug
    com.cjyc.carcircle.api.dao: debug




cjyc:
  swagger:
    enabled: true
    title: 韵车对外接口文档
    description: 长久韵车对外接口文档
    version: 2.0.1
    basePackage: com.cjyc.foreign.api.controller
    groupName: 韵车对外接口
    usePathMapping: false