
#
#local为本机环境(127.0.0.1)配置
#

server:
  #服务端口
  port: 9500
  #服务baseURl
  servlet:
    context-path: /cjyc/common
  #https访问
#  ssl:
#    key-store: classpath:server.jks
#    key-store-password: Vf1@MFJkhRyOSxm2
#    keyStoreType: JKS

spring:
  #项目名
  #application:
    #name: yunche-api

  ##静态资源本地位置(最后的/记得加)
  resources:
    static-locations: file:D:\\upload\\
  #静态资源过滤url
  mvc:
    static-path-pattern: /**

  ##actuator管理
  management:
    endpoints:
      enabled-by-default: true
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: always

  ##数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.96.231:3306/cjyc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Qaz123$%^231#
    #连接池
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: YuncheHikari
      max-lifetime: 1800000
      connection-timeout: 30000
      #connection-test-query: select 1

  ##Mybatis
  ##mybatis:
    ##mapper-locations: classpath:mapper/*Mapper.xml
    ##type-aliases-package: com.cjyc.customer.api.entity
    #config-location : classpath:mybatis-config.xml

  ##缓存
  redis:
    host: 192.168.225.11
    port: 6379
    password:
    #Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    timeout: 1000ms
    #连接池，redis2.x默认连接池
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 32
        #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 300ms
        #连接池中的最大空闲连接 默认 8
        max-idle: 16
        #连接池中的最小空闲连接 默认 0
        min-idle: 8



  ##自定义参数

  ##极光推送
  JPush:
      appKey: 8a4abf674ba61fc9c47d6616
      masterSecret: 6fc93a75e2f813f4798e88ff

##ping++
Ping++:
    businessCode: 200604000004527
    apikey: sk_test_40WD00COyLKOKKCiD8vH04qL
    customer:
       appid: app_WHKWv9XDWTyPz1G8
       webhooks: http://39.106.134.87:80/manycc/pingpay/webhooksNotice
    driver:
       appid: app_XzvvzPDmDm1GbTi1
       webhooks: http://39.106.134.87:80/manycc/pingpay/webhooksNotice
    salesman:
       appid: app_LSm9WLS4SmLSSC48
       webhooks: http://39.106.134.87:80/manycc/pingpay/webhooksNotice

##SALT
salt:
   customer_salt: YCcustomersalt
   driver_salt: YCdriversalt
   salesman_salt: YCsalesmansalt

##TOKEN
token:
  ##过期时间（秒）
  expires: 1800

##短信
messages:
  ##短信时效(分钟)
  expires: 5
  ##单日最大发送条数
  daylimit: 20


#mybatis-plus
mybatis-plus:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.cjyc.common.entity
   configuration.map-underscore-to-camel-case: true
